// ===== CATÁLOGO PERFUMES EUROPEOS =====
// Extraído del catálogo oficial Tienda ATE — Setiembre (actualizado)
const CATALOG = {
  // HOMBRE
  'M220':  { name: 'ANIMALE', brand: 'ANIMALE', gender: 'H' },
  'M1111': { name: 'KING OF SEDUCTION', brand: 'ANTONIO BANDERAS', gender: 'H' },
  'M1241': { name: '9PM', brand: 'AFNAN', gender: 'H' },
  'M1242': { name: '9AM DIVE', brand: 'AFNAN', gender: 'H' },
  'M7507': { name: 'AMBER OUD AQUA DUBAI', brand: 'AL HARAMAIN PERFUMES', gender: 'H' },
  'M5005': { name: 'AMBER OUD GOLD', brand: 'AL HARAMAIN PERFUMES', gender: 'H' },
  'M1206': { name: 'AMBER OUD', brand: 'AL HARAMAIN PERFUMES', gender: 'H' },
  'M7502': { name: 'FOREVER WANTED ELIXIR', brand: 'AZZARO', gender: 'H' },
  'M5002': { name: 'MOST WANTED INTENSE', brand: 'AZZARO', gender: 'H' },
  'M1144': { name: 'WANTED', brand: 'AZZARO', gender: 'H' },
  'M5003': { name: 'WANTED BY NIGHT AZZARO', brand: 'AZZARO', gender: 'H' },
  'M1255': { name: 'KING', brand: 'BHARARA', gender: 'H' },
  'M1208': { name: 'HERO DE BURBERRY', brand: 'BURBERRY', gender: 'H' },
  'M156':  { name: 'BULGARI FOR MEN', brand: 'BVLGARI', gender: 'H' },
  'M899':  { name: 'CK ONE', brand: 'CALVIN KLEIN', gender: 'H' },
  'M187':  { name: 'ETERNITY FOR MEN', brand: 'CALVIN KLEIN', gender: 'H' },
  'M1181': { name: '212 HEROES CH', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M779':  { name: '212 MEN', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M930':  { name: '212 SEXY MEN', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M1179': { name: '212 VIP BLACK RED', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M1156': { name: '212 VIP BLACK', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M1269': { name: '212 VIP BLACK ELIXIR', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M1058': { name: '212 VIP DE CH', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M1184': { name: '212 VIP MEN WINS', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M1174': { name: 'BAD BOY', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M1194': { name: 'BAD BOY COBALT', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M1218': { name: 'BAD BOY XTRME', brand: 'CAROLINA HERRERA', gender: 'H' },
  'M768':  { name: 'ALLURE', brand: 'CHANEL', gender: 'H' },
  'M1025': { name: 'BLEU DE CHANEL', brand: 'CHANEL', gender: 'H' },
  'M1173': { name: 'ADVENTUS', brand: 'CREED', gender: 'H' },
  'M1186': { name: 'SILVER MOUNTAIN', brand: 'CREED', gender: 'H' },
  'M1195': { name: 'CR7 ORIGINS', brand: 'CRISTIANO RONALDO', gender: 'H' },
  'M1138': { name: 'LEGACY', brand: 'CRISTIANO RONALDO', gender: 'H' },
  'M190':  { name: 'COOL WATER', brand: 'DAVIDOFF', gender: 'H' },
  'M185':  { name: 'FARENHEIT', brand: 'DIOR', gender: 'H' },
  'M1258': { name: 'SAUVAGE EAU FORTE', brand: 'DIOR', gender: 'H' },
  'M1215': { name: 'SAUVAGE ELIXIR', brand: 'DIOR', gender: 'H' },
  'M1141': { name: 'SAUVAGE', brand: 'DIOR', gender: 'H' },
  'M233':  { name: 'DOLCE & GABBANA POUR HOMME', brand: 'DOLCE&GABBANA', gender: 'H' },
  'M1177': { name: 'K D&G', brand: 'DOLCE&GABBANA', gender: 'H' },
  'M951':  { name: 'LIGHT BLUE POUR HOMME', brand: 'DOLCE&GABBANA', gender: 'H' },
  'M1006': { name: 'FERRARI BLACK', brand: 'FERRARI', gender: 'H' },
  'M631':  { name: 'ACQUA DE GIO', brand: 'GIORGIO ARMANI', gender: 'H' },
  'M1129': { name: 'ACQUA DI GIO PROFUMO', brand: 'GIORGIO ARMANI', gender: 'H' },
  'M1187': { name: 'ACQUA DI GIO PROFUNDO', brand: 'GIORGIO ARMANI', gender: 'H' },
  'M1108': { name: 'ACQUA DI GIO BLUE', brand: 'GIORGIO ARMANI', gender: 'H' },
  'M902':  { name: 'ARMANI BLACK CODE', brand: 'GIORGIO ARMANI', gender: 'H' },
  'M1153': { name: 'STRONGER WITH YOU', brand: 'GIORGIO ARMANI', gender: 'H' },
  'M7504': { name: 'STRONGER WITH YOU INTENSELY', brand: 'GIORGIO ARMANI', gender: 'H' },
  'M1089': { name: 'GENTLEMEN ONLY', brand: 'GIVENCHY', gender: 'H' },
  'M772':  { name: 'PI', brand: 'GIVENCHY', gender: 'H' },
  'M193':  { name: 'BOSS', brand: 'HUGO BOSS', gender: 'H' },
  'M762':  { name: 'BOSS BOTTLE', brand: 'HUGO BOSS', gender: 'H' },
  'M1198': { name: 'BOSS BOTTLE MARINE', brand: 'HUGO BOSS', gender: 'H' },
  'M1224': { name: 'BOSS BOTTLED ELIXIR', brand: 'HUGO BOSS', gender: 'H' },
  'M1216': { name: 'BOSS BOTTLED PACIFIC', brand: 'HUGO BOSS', gender: 'H' },
  'M898':  { name: 'HUGO', brand: 'HUGO BOSS', gender: 'H' },
  'M729':  { name: 'JEAN PAUL GAULTIER', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M1234': { name: 'LE BEAU', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M1267': { name: 'LE BEAU PARADISE GARDEN', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M7513': { name: 'LE MALE ELIXIR ABSOLU', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M1252': { name: 'LE MALE ELIXIR', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M7506': { name: 'LE MALE LE PARFUM', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M7515': { name: 'SCANDAL POUR HOMME INTENSE', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M1189': { name: 'SCANDAL POUR HOMME', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M5010': { name: 'ULTRA MALE', brand: 'JEAN PAUL GAULTIER', gender: 'H' },
  'M1214': { name: 'MAN AQUA', brand: 'JIMMY CHOO', gender: 'H' },
  'M864':  { name: 'LACOSTE POUR HOMME', brand: 'LACOSTE FRAGRANCES', gender: 'H' },
  'M1087': { name: 'NOIR L.12.12', brand: 'LACOSTE FRAGRANCES', gender: 'H' },
  'M7501': { name: 'ASAD BOURBON', brand: 'LATTAFA PERFUMES', gender: 'H' },
  'M7510': { name: 'ASAD ELIXIR', brand: 'LATTAFA PERFUMES', gender: 'H' },
  'M5011': { name: 'BADE\'E AL OUD HONOR & GLORY', brand: 'LATTAFA PERFUMES', gender: 'H' },
  'M5006': { name: 'BADE\'E AL OUD SUBLIME', brand: 'LATTAFA PERFUMES', gender: 'H' },
  'M5007': { name: 'KHAMRAH QAHWA', brand: 'LATTAFA PERFUMES', gender: 'H' },
  'M7508': { name: 'KHAMRAH', brand: 'LATTAFA PERFUMES', gender: 'H' },
  'MF3':   { name: 'CITY OF STARS', brand: 'LOUIS VUITTON', gender: 'H' },
  'M7509': { name: 'IMAGINATION', brand: 'LOUIS VUITTON', gender: 'H' },
  'M7516': { name: 'OMBRE NOMADE', brand: 'LOUIS VUITTON', gender: 'H' },
  'M7514': { name: 'OUD MARACUJÁ', brand: 'MAISON CRIVELLI', gender: 'H' },
  'M912':  { name: 'STAR WALKER', brand: 'MONTBLANC', gender: 'H' },
  'M1190': { name: 'TOY BOY', brand: 'MOSCHINO', gender: 'H' },
  'M943':  { name: 'NAUTICA VOYAGE', brand: 'NAUTICA', gender: 'H' },
  'M7503': { name: 'ALTHAÏR', brand: 'PARFUMS DE MARLY', gender: 'H' },
  'M1266': { name: 'LAYTON', brand: 'PARFUMS DE MARLY', gender: 'H' },
  'M1213': { name: 'LUNA ROSA CARBON PRADA', brand: 'PRADA', gender: 'H' },
  'M1160': { name: '1 MILLION LUCKY', brand: 'RABANNE', gender: 'H' },
  'M981':  { name: '1 MILLION', brand: 'RABANNE', gender: 'H' },
  'M1098': { name: 'BLACK XS L\'APHRODISIAQUE', brand: 'RABANNE', gender: 'H' },
  'M1142': { name: 'INVICTUS AQUA', brand: 'RABANNE', gender: 'H' },
  'M1200': { name: 'INVICTUS PLATINIUM', brand: 'RABANNE', gender: 'H' },
  'M1230': { name: 'INVICTUS VICTORY', brand: 'RABANNE', gender: 'H' },
  'M7505': { name: 'INVICTUS VICTORY ABSOLU', brand: 'RABANNE', gender: 'H' },
  'M1095': { name: 'INVICTUS', brand: 'RABANNE', gender: 'H' },
  'M1235': { name: 'INVICTUS VICTORY ELIXIR', brand: 'RABANNE', gender: 'H' },
  'M1254': { name: 'MILLION GOLD', brand: 'RABANNE', gender: 'H' },
  'M7512': { name: 'MILLION GOLD ELIXIR', brand: 'RABANNE', gender: 'H' },
  'M1236': { name: 'ONE MILLION ELIXIR', brand: 'RABANNE', gender: 'H' },
  'M1146': { name: 'ONE MILLION PRIVE', brand: 'RABANNE', gender: 'H' },
  'M1217': { name: 'ONE MILLION ROYALE', brand: 'RABANNE', gender: 'H' },
  'M5':    { name: 'PACO RABANNE POUR HOMME', brand: 'RABANNE', gender: 'H' },
  'M1182': { name: 'PHANTOM', brand: 'RABANNE', gender: 'H' },
  'M1221': { name: 'PHANTOM PARFUM', brand: 'RABANNE', gender: 'H' },
  'M1010': { name: 'XS BLACK', brand: 'RABANNE', gender: 'H' },
  'M709':  { name: 'POLO', brand: 'RALPH LAUREN', gender: 'H' },
  'M1093': { name: 'POLO RED', brand: 'RALPH LAUREN', gender: 'H' },
  'M1238': { name: 'FERRAGAMO UOMO', brand: 'SALVATORE FERRAGAMO', gender: 'H' },
  'M201':  { name: 'TED LAPIDUS POUR HOMME', brand: 'TED LAPIDUS', gender: 'H' },
  'MF1':   { name: 'CEREZA', brand: 'TOM FORD', gender: 'H' },
  'MF2':   { name: 'OMBRE LEATHER', brand: 'TOM FORD', gender: 'H' },
  'M1205': { name: 'TOBACCO VAINILLA', brand: 'TOM FORD', gender: 'H' },
  'M726':  { name: 'TOMMY', brand: 'TOMMY HILFIGER', gender: 'H' },
  'M1227': { name: 'BORN IN ROMA INTENSE', brand: 'VALENTINO', gender: 'H' },
  'M7511': { name: 'UOMO BORN IN ROMA CORAL FANTASY', brand: 'VALENTINO', gender: 'H' },
  'M1256': { name: 'EROS ENERGY', brand: 'VERSACE', gender: 'H' },
  'M1220': { name: 'EROS FLAME', brand: 'VERSACE', gender: 'H' },
  'M1092': { name: 'EROS', brand: 'VERSACE', gender: 'H' },
  'M989':  { name: 'VERSACE POUR HOMME', brand: 'VERSACE', gender: 'H' },
  'M1239': { name: 'SPICEBOMB INFRARED', brand: 'VIKTOR&ROLF', gender: 'H' },
  'M812':  { name: 'SWISS ARMY', brand: 'VICTORINOX', gender: 'H' },
  'M5009': { name: 'ERBA PURA', brand: 'XERJOFF', gender: 'H' },
  'M1207': { name: 'Y DE YSL', brand: 'YVES SAINT LAURENT', gender: 'H' },
  'M1212': { name: 'CLUB DE NUIT', brand: 'ARMAF', gender: 'H' },
  'M5008': { name: 'ODYSSEY MANDARIN SKY', brand: 'ARMAF', gender: 'H' },
  // MUJER
  'F1240': { name: 'ARI', brand: 'ARIANA GRANDE', gender: 'M' },
  'F1284': { name: 'CLOUD', brand: 'ARIANA GRANDE', gender: 'M' },
  'F1349': { name: 'CLOUD PINK', brand: 'ARIANA GRANDE', gender: 'M' },
  'F1325': { name: 'MOD VANILLA', brand: 'ARIANA GRANDE', gender: 'M' },
  'F1393': { name: 'R.E.M. CHERRY ECLIPSE', brand: 'ARIANA GRANDE', gender: 'M' },
  'F1355': { name: 'CLUB DE NUIT WOMAN', brand: 'ARMAF', gender: 'M' },
  'F1347': { name: 'BILLIE EILISH', brand: 'BILLIE EILISH', gender: 'M' },
  'F942':  { name: 'FANTASY', brand: 'BRITNEY SPEARS', gender: 'M' },
  'F1283': { name: 'BURBERRY HER', brand: 'BURBERRY', gender: 'M' },
  'F887':  { name: 'AMOR AMOR', brand: 'CACHAREL', gender: 'M' },
  'F102':  { name: 'ANAIS ANAIS', brand: 'CACHAREL', gender: 'M' },
  'F128':  { name: 'ETERNITY', brand: 'CALVIN KLEIN', gender: 'M' },
  'F717':  { name: '212', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1305': { name: '212 HEROES FOREVER YOUNG', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F917':  { name: '212 SEXY', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1064': { name: '212 VIP', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1225': { name: '212 VIP CLUB EDITION', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1178': { name: '212 VIP ROSE', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1285': { name: '212 VIP ROSE EXTRA', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F129':  { name: 'CAROLINA HERRERA', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1000': { name: 'CH', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1333': { name: 'GOOD GIRL BLUSH', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F7509': { name: 'GOOD GIRL BOWTASTIC EDITION', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1354': { name: 'GOOD GIRL DAZZLING GARDEN', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1249': { name: 'GOOD GIRL', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1410': { name: 'LA BOMBA', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F1295': { name: 'VERY GOOD GIRL CH', brand: 'CAROLINA HERRERA', gender: 'M' },
  'F851':  { name: 'CHANCE', brand: 'CHANEL', gender: 'M' },
  'F7506': { name: 'CHANCE EAU SPLENDIDE', brand: 'CHANEL', gender: 'M' },
  'F111':  { name: 'CHANEL N.5', brand: 'CHANEL', gender: 'M' },
  'F131':  { name: 'COCO CHANEL', brand: 'CHANEL', gender: 'M' },
  'F815':  { name: 'COCO MADEMOISELLE', brand: 'CHANEL', gender: 'M' },
  'F190':  { name: 'COOL WATER FOR WOMAN', brand: 'DAVIDOFF', gender: 'M' },
  'F721':  { name: 'HYPNOTIC POISON', brand: 'DIOR', gender: 'M' },
  'F754':  { name: 'JADORE', brand: 'DIOR', gender: 'M' },
  'F1041': { name: 'MISS DIOR DE CHERIE', brand: 'DIOR', gender: 'M' },
  'F7508': { name: 'MISS DIOR ESSENCE', brand: 'DIOR', gender: 'M' },
  'F7504': { name: 'MISS DIOR PARFUM 2024', brand: 'DIOR', gender: 'M' },
  'F16':   { name: 'POISON', brand: 'DIOR', gender: 'M' },
  'F1239': { name: 'POISON GIRL', brand: 'DIOR', gender: 'M' },
  'F1352': { name: 'DEVOTION DE DOLCE GABBANA', brand: 'DOLCE&GABBANA', gender: 'M' },
  'F848':  { name: 'LIGHT BLUE', brand: 'DOLCE&GABBANA', gender: 'M' },
  'F913':  { name: 'BE DELICIUS', brand: 'DONNA KARAN', gender: 'M' },
  'F500':  { name: 'RED DOOR', brand: 'ELIZABETH ARDEN', gender: 'M' },
  'F924':  { name: 'ROCKING RIO', brand: 'ESCADA', gender: 'M' },
  'F631':  { name: 'ACQUA DI GIO', brand: 'GIORGIO ARMANI', gender: 'M' },
  'F1300': { name: 'MY WAY', brand: 'GIORGIO ARMANI', gender: 'M' },
  'F142':  { name: 'AMARIGE', brand: 'GIVENCHY', gender: 'M' },
  'F960':  { name: 'ANGELES Y DEMONIOS', brand: 'GIVENCHY', gender: 'M' },
  'F1335': { name: 'IRRESISTIBLE ROSE VELVET', brand: 'GIVENCHY', gender: 'M' },
  'F683':  { name: 'ORGANZA', brand: 'GIVENCHY', gender: 'M' },
  'F789':  { name: 'BOSS WOMAN', brand: 'HUGO BOSS', gender: 'M' },
  'F707':  { name: 'HUGO BOSS WOMAN', brand: 'HUGO BOSS', gender: 'M' },
  'F1381': { name: 'GAULTIER DIVINE', brand: 'JEAN PAUL GAULTIER', gender: 'M' },
  'F1321': { name: 'SCANDAL LE PARFUM', brand: 'JEAN PAUL GAULTIER', gender: 'M' },
  'F1266': { name: 'SCANDAL', brand: 'JEAN PAUL GAULTIER', gender: 'M' },
  'F1108': { name: 'MEOW', brand: 'KATY PERRY', gender: 'M' },
  'F786':  { name: 'FLOWER', brand: 'KENZO', gender: 'M' },
  'F1116': { name: 'LA VIE EST BELLE', brand: 'LANCÔME', gender: 'M' },
  'F1379': { name: 'LA VIE EST BELLE L\'ELIXIR', brand: 'LANCÔME', gender: 'M' },
  'F7507': { name: 'ECLAIRE', brand: 'LATTAFA PERFUMES', gender: 'M' },
  'F5006': { name: 'YARA CANDY', brand: 'LATTAFA PERFUMES', gender: 'M' },
  'F7505': { name: 'YARA ELIXIR', brand: 'LATTAFA PERFUMES', gender: 'M' },
  'F7502': { name: 'YARA TOUS', brand: 'LATTAFA PERFUMES', gender: 'M' },
  'F1377': { name: 'YARA', brand: 'LATTAFA PERFUMES', gender: 'M' },
  'F1322': { name: 'SANTAL 33', brand: 'LE LABO', gender: 'M' },
  'F1319': { name: 'BACCARAT ROUGE 540', brand: 'MAISON FRANCIS KURKDJIAN', gender: 'M' },
  'F656':  { name: 'ANGEL', brand: 'MUGLER', gender: 'M' },
  'F1359': { name: 'DELINA DE MARLY', brand: 'PARFUMS DE MARLY', gender: 'M' },
  'F1012': { name: 'CAN CAN', brand: 'PARIS HILTON', gender: 'M' },
  'F976':  { name: 'HEIRESS', brand: 'PARIS HILTON', gender: 'M' },
  'F920':  { name: 'PARIS HILTON', brand: 'PARIS HILTON', gender: 'M' },
  'F6002': { name: 'PRADA PARADOXE', brand: 'PRADA', gender: 'M' },
  'F1317': { name: 'FAME PACO RABBANE', brand: 'RABANNE', gender: 'M' },
  'F1059': { name: 'LADY MILLION', brand: 'RABANNE', gender: 'M' },
  'F1366': { name: 'LADY MILLION EMPIRE', brand: 'RABANNE', gender: 'M' },
  'F1276': { name: 'LADY MILLION LUCKY', brand: 'RABANNE', gender: 'M' },
  'F1338': { name: 'LADY MILLION ROYALE', brand: 'RABANNE', gender: 'M' },
  'F1378': { name: 'MILLION GOLD FOR HER', brand: 'RABANNE', gender: 'M' },
  'F1226': { name: 'OLYMPEA', brand: 'RABANNE', gender: 'M' },
  'F783':  { name: 'RALPH', brand: 'RALPH LAUREN', gender: 'M' },
  'F1125': { name: 'SELENA GOMEZ', brand: 'SELENA GOMEZ', gender: 'M' },
  'F1193': { name: 'SOFIA VERGARA', brand: 'SOFIA VERGARA', gender: 'M' },
  'F7500': { name: 'CHEIROSA \'62', brand: 'SOL DE JANEIRO', gender: 'M' },
  'F7501': { name: 'RIO RADIANCE', brand: 'SOL DE JANEIRO', gender: 'M' },
  'F687':  { name: 'TOMMY GIRL', brand: 'TOMMY HILFIGER', gender: 'M' },
  'F1368': { name: 'BORN IN ROMA DONNA', brand: 'VALENTINO', gender: 'M' },
  'F1341': { name: 'BOMBSHELL ISLE', brand: 'VICTORIA\'S SECRET', gender: 'M' },
  'F1342': { name: 'BOMBSHELL SUNDRENCHED', brand: 'VICTORIA\'S SECRET', gender: 'M' },
  'F6003': { name: 'BLACK OPIUM', brand: 'YVES SAINT LAURENT', gender: 'M' },
  'F1298': { name: 'LIBRE', brand: 'YVES SAINT LAURENT', gender: 'M' },
  'F97':   { name: 'PARIS', brand: 'YVES SAINT LAURENT', gender: 'M' },
};

// Buscar en catálogo por código
function lookupCatalog(code) {
  return CATALOG[code.toUpperCase()] || null;
}
